### ISSUE TITLE
Odd conversion from UTF-8 to ISO-8859-1

### ISSUE THREAD

**Issue by JoakimLofgren** [gggeek/phpxmlrpc#33] opened 2016-02-25 22:15 UTC
Compatible ISO-8859-1 characters like åäö are converted into numeric HTML entities when they don't need to be...

In my opinion only characters that are unsupported or clashes with XML, e.g. <, > and others, should be converted into numeric HTML entities.

If I remember correctly this was not the case in the version 3.0.1 of this library.

**Comment by JoakimLofgren** [comment] 2016-02-25 22:19
I've started playing with some possible solutions (I referenced the commit to this issue).

@gggeek Any thoughts or concerns on my WIP stuff?

**Comment by gggeek** [comment] 2016-02-28 19:19
Thanks for providing test cases.

Just to be sure that I understand correctly the situation and can reproduce the problem:
- the problem arises when the lib receives latin-1 chars from external sources, and passes utf8 to the app / viceversa / both ways ? Is there a charset declaration in the xml prolog and/or a BOM involved?
- you are providing test code; did you investigate the root of the problem?
- are the 2 test classes in your code alternatives to do the exact same thing?

I ask because a few fixes were indeed made to the code in the area of charset handling, to make sure that some corner cases are properly handled, and I would expect the lib to actually fare better...

**Comment by JoakimLofgren** [comment] 2016-02-28 19:37
The problem is when you have a UTF-8 file with `å` and then you try to send it as ISO-8859-1 (e.g. it goes into [this case](https://github.com/gggeek/phpxmlrpc/blob/master/src/Helper/Charset.php#L117) in the Charset file). 

Well the charset declaration or the BOM is not the issue as there are no "garbled" characters.

I ran into the issue when trying to send XML with the [Client](https://github.com/gggeek/phpxmlrpc/blob/master/src/Client.php#L454). It seems to be that it HTML entity encodes characters which need not be.

The CharsetFixTest file is my attempt at writing a fix (with the code in the test file) and should be removed before being merged.

**Comment by DianonForce** [comment] 2016-03-15 09:47
Hi Guys,
is there a posible solution or a workaround for this problem? 
I have the problem, that i have to make a connection to an xmlrpc-server, wich need to get user information from me.  Any idiot decided, that my username contains 'ö' insted of 'oe', so the 'ö' is converted in '#&246;' wich give me an error 'no such user' as respond from xmlrpc-server.

**Comment by gggeek** [comment] 2016-03-16 12:43
Sorry, I have been pretty busy to work on this. I will do my best to find enough time the upcoming weekend

**Comment by gggeek** [comment] 2016-03-26 22:37
@DianonForce the simplest workaround seems to me to set
    `$client->request_charset_encoding = 'UTF-8';`
did you try it ?

**Comment by gggeek** [comment] 2016-03-27 00:20
Fixed in version 4.0.1.
Thanks @JoakimLofgren, I incorporated your test case, albeit slightly reduced.
As for version 3.0.1, I checked the code for character encoding conversion and it was the same as it in in version 4, so if this was not happening before, it must have been a long time ago.

**Closed** 2016-03-27 00:20 UTC

**Comment by JoakimLofgren** [comment] 2016-03-27 13:42
Thanks @gggeek 

I'll check my use case on Tuesday. :)
