### ISSUE TITLE
curl error 28 while downloading https://repo.packagist.org/p2/vendor/package.json

### ISSUE THREAD

**Issue by ghost** [gggeek/phpxmlrpc#87] opened 2021-10-28 16:50 UTC
Following the instructions on https://github.com/gggeek/phpxmlrpc/blob/master/INSTALL.md 
```
$ composer require phpxmlrpc/phpxmlrpc:4
```
I get

> https://repo.packagist.org could not be fully loaded (curl error 28 while downloading https://repo.packagist.org/packages.json: Failed to connect to repo.packagist.org port 443: Connection timed out), package information was loaded from the local cache and may be out of date

```
[Composer\Downloader\TransportException]
curl error 28 while downloading https://repo.packagist.org/p2/vendor/package.json: Failed to connect to repo.packagist.org port 443: Connection timed out
```
![image](https://user-images.githubusercontent.com/10009595/139299634-d64426c8-1cc1-4021-b51f-a6799596d6a4.png)

probaly due to a failure I made.

**Comment by gggeek** [comment] 2021-10-31 21:07
PS: I asked the lead dev of Composer, and he said that the problem is in the curl timeout, not in the gact that composer tries to access that page.
Is there a reverse proxy in place?

**Comment by gggeek** [comment] 2021-12-08 17:39
See also this ticket: https://github.com/composer/composer/issues/10161 - it seems that the upcoming Composer 2.2 will be more prone to retry failed connections to Packagist

**Comment by gggeek** [comment] 2022-12-06 17:47
1 year and no feedback - closing

**Closed as completed by gggeek** 2022-12-06 17:47 UTC
Labels: waiting for feedback

**Comment by ecxod** [comment] 2023-05-09 01:38
please check if you have "mod_security" or "mod_security2" enabled in your apache2
If you have access to the settings they are usually in /etc/modsecurity you can go like this :

mcedit  /etc/modsecurity/crs/packagist.conf

```
SecRule SERVER_NAME "composer.org" \
    "id:1000,phase:1,t:none,nolog,allow,ctl:ruleEngine=Off"

SecRule SERVER_NAME "packagist.org" \
    "id:1001,phase:1,t:none,nolog,allow,ctl:ruleEngine=Off"

SecRule REMOTE_ADDR "@ipMatch 185.85.2.0/22" \
    "id:1002,phase:1,t:none,nolog,allow,ctl:ruleEngine=Off"

SecRule REMOTE_ADDR "@ipMatch 146.59.12.128/25" \
    "id:1003,phase:1,t:none,nolog,allow,ctl:ruleEngine=Off"
```
then 
```
service apache2 restart
```
and have fun

**Comment by ingy-elkhateeb** [comment] 2024-11-03 19:30
In my case it was solved by increasing the default timeout of curl using this command 
`composer config -g process-timeout 2000` the repo was giving me 404 as well but this command solved my issue I hope it solve yours too :)
