### ISSUE TITLE
Issue with Content-Length in HTTP header

### ISSUE THREAD

**Issue by henderikus** [gggeek/phpxmlrpc#75] opened 2020-05-20 10:14 UTC
When sending XML messages larger than 8KB somehow the last peace(1 or 2 bytes) is missing when received. This only happens when HTTPS is used.

When disable the line with  `header('Content-Length: ' . (int)strlen($payload));` in file src/Server.php or increase the Content-Length with 1 it is working fine.

I am using PHP 7.3.10, Apache 2.4.39 with XML-RPC for PHP version 4.4.2.

Any help would be appreciated.

**Comment by gggeek** [comment] 2020-05-20 13:28
Hello.
Interesting (and tricky) finding...

I presume that you are using this library both on the client and the server side?

Would you be able to dump client-side the headers in the http response gotten from the server, to check if those are coming in double?

Also: are you enabling/allowing the compression of http responses?

**Comment by henderikus** [comment] 2020-05-20 16:15
_I presume that you are using this library both on the client and the server side?_
That is correct.


```
HTTP/1.1 200 OK
Date: Wed, 20 May 2020 16:07:22 GMT
Server: Apache/2.4.39 (Win64) OpenSSL/1.1.1b PHP/7.3.10
X-Powered-By: PHP/7.3.10
Set-Cookie: PHPSESSID=evp8u4qne83t7u6id5l8uk69rb; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Vary: Accept-Charset
Content-Length: 8717
Content-Type: text/xml; charset=UTF-8
```

_Also: are you enabling/allowing the compression of http responses?_
I am not 100% sure, but I think it is disabled. How can I confirm this? zlib.output_compression = off in phpinfo().

**Comment by gggeek** [comment] 2020-05-23 13:32
Thanks for the detailed infos.
Indeed it seems that the response headers are correct - in the sense that the Content-Length is not present twice (as seen in the 'raw_data').
There seems to be no compression of the response, either, which rules out a few possible sources of trouble.
I guess that the next step then would be for me to try to replicate the issue.

The only thing I can think about atm is the presence of "weird" chars in the response, that would make the computation of the length wrong (such as ascii non printable stuff, maybe NUL or Backspace?).
 
If there is no sensitive information in it, I'd like for you to send over a copy of the full xml response payload.

Another test would be to force the server to encode its response to ASCII instead of UTF8.
In order to achieve that, add `$client->accepted_charset_encodings = array('US-ASCII');` before the `send` call on the client side...

**Comment by henderikus** [comment] 2020-05-25 08:48
>If there is no sensitive information in it, I'd like for you to send over a copy of the full xml response payload.

```
$retval = array("a" => "aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa112823749817238947192873498712983489218943791823238179487129834aaa11282374981722aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");

return new xmlrpcresp(php_xmlrpc_encode($retval));
```

>Another test would be to force the server to encode its response to ASCII instead of UTF8.
In order to achieve that, add $client->accepted_charset_encodings = array('US-ASCII'); before the send call on the client side...
This has the same effect.

**Comment by gggeek** [comment] 2020-05-25 09:01
Ok, I'll try to finf some time to test today

**Comment by henderikus** [comment] 2020-05-25 13:58
If I can do something to help let me know.

**Comment by henderikus** [comment] 2020-05-28 19:39
I found something out.

Apache overwrites the Content-Length when it is 8000 bytes or smaller, when it is greater then 8000 it adds the `Transfer-Encoding: Chunked` to the headers. This is something in HTTP 1.1.  

Because the Content-Length is set in Server.php the Transfer-Encoding header is not set.

In my case(with Apache) removing the Content-Length, would fix my issue. I am not sure what will happen with other webservers...

**Comment by gggeek** [comment] 2020-05-28 21:03
Thanks for the investigation.
Interesting finding. Not sure what would be the best fix though.
1. we should investigate if is this something happening only with Apache or also Nginx/Lighty
2. also, can you confirm that this only affects https calls and not plain http ones?
3. the fact that the library does send the content-length header is not an accident - it does force some specific behaviour in the web servers, but it is also stated in the xmlrpc spec that "Content-Length must be present and correct." (although I dare say that when Dave Winer wrote it he made a mistake in hardcoding too many details regarding usage of the http protocol that could have been left out by simply stating 'http 1.1 compliant')
4. if the fact that the php app specifies a `Content-Length` header does make Apache skip adding the `Transfer-Encoding: Chunked` response header, then I'd reasonably expect it as well _not_ to do the chunking. As far as my understanding of the situation goes, at the moment I think we can ascribe the bug to Apache...

ps: weird that no one reported this problem in many years of usage of the library...
pps: googling around I found in the first few hits a similar issue with cakephp (https://github.com/cakephp/cakephp/issues/7639). Not sure that I get what their fix was though

**Comment by gggeek** [comment] 2020-05-28 21:19
One finding: you might be able to work around this bug by forcing the client to use the http 1.0 protocol (by passing `http10` as 3rd param to the `send()` call and adding a `setUseCurl(always)` call)

**Comment by gggeek** [comment] 2020-05-28 21:33
Similar problem: sending byte-range requests to a php script on apache fails when response is above 8K. https://bugs.php.net/bug.php?id=45945. Is 8000 an apache or mod_php hardcoded buffer size?

**Comment by gggeek** [comment] 2020-05-29 07:26
Similar problem: sending byte-range requests to a php script on apache fails when response is above 8K. https://bugs.php.net/bug.php?id=45945. Is 8000 an apache or mod_php hardcoded buffer size?

**Comment by henderikus** [comment] 2020-05-29 15:43
>we should investigate if is this something happening only with Apache or also Nginx/Lighty

Below the 8000bytes Apache is sets the Content-Length, Nginx doesn't.  

If I remove the line that sets the Content-Length in src/Server.php, Nginx is nog setting the Content-Length, but instead adds  " Transfer-Encoding: Chunked" .

Below you can see  there is a difference of 2 in Content-Length between how Apache sets the Content-Length and the XMLRPC library sets it:

**Apache - HTTP:**
 
```
Date: Fri, 29 May 2020 14:39:40 GMT
Server: Apache/2.4.39 (Win64) OpenSSL/1.1.1b PHP/7.3.10
X-Powered-By: PHP/7.3.10
Set-Cookie: PHPSESSID=pgj3m5mdui2oqhnvub61opseq8; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Vary: Accept-Charset
Content-Length: 245
Connection: close
Content-Type: text/xml; charset=UTF-8

 
 
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<params>
<param>
<value><struct>
<member><name>a</name>
<value><string>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</string></value>
</member>
</struct></value>
</param>
</params>
</methodResponse>
```
 
 
 
**Apache - HTTPS:**
 
```
Date: Fri, 29 May 2020 14:38:19 GMT
Server: Apache/2.4.39 (Win64) OpenSSL/1.1.1b PHP/7.3.10
X-Powered-By: PHP/7.3.10
Set-Cookie: PHPSESSID=tio107pca5mglle7mbf4em59qm; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Vary: Accept-Charset
Content-Length: 245
Content-Type: text/xml; charset=UTF-8
 
 
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<params>
<param>
<value><struct>
<member><name>a</name>
<value><string>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</string></value>
</member>
</struct></value>
</param>
</params>
</methodResponse>
 
```
 
 
 
 
**NGINX-HTTP:**
 
```
Server: nginx/1.18.0
Date: Fri, 29 May 2020 14:35:11 GMT
Content-Type: text/xml; charset=UTF-8
Content-Length: 243
Connection: close
X-Powered-By: PHP/7.3.10
Set-Cookie: PHPSESSID=frgghlinj8gfknhdierff8gstg; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Vary: Accept-Charset
 
 
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<params>
<param>
<value><struct>
<member><name>a</name>
<value><string>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</string></value>
</member>
</struct></value>
</param>
</params>
</methodResponse>
```
 
 
**NGINX-HTTPS:**
 
```
Server: nginx/1.18.0
Date: Fri, 29 May 2020 14:36:19 GMT
Content-Type: text/xml; charset=UTF-8
Content-Length: 243
Connection: keep-alive
X-Powered-By: PHP/7.3.10
Set-Cookie: PHPSESSID=soqp8c7h4p0m8fsnru955p14ms; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Vary: Accept-Charset
 
 
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<params>
<param>
<value><struct>
<member><name>a</name>
<value><string>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</string></value>
</member>
</struct></value>
</param>
</params>
</methodRespons
```
>also, can you confirm that this only affects https calls and not plain http ones?
It is only with HTTPS calls. As seen above.

So I think the way Apache determines the Content-Length is the right way.

**Comment by henderikus** [comment] 2020-05-30 11:58
>ps: weird that no one reported this problem in many years of usage of the library...
Maybe because it only happens with large XML messages. Also I have tested three XmlRpc clients, with the example above, they all handle the Content-Length differently:

- PHP Libcurl: Only works when set to 245
- CookComputing XmlRpcV2: Totally ignores it
- Chrome extension XML-RPC Client: Work when set to 243 or higher.

>One finding: you might be able to work around this bug by forcing the client to use the http 1.0 protocol (by passing http10 as 3rd param to the send() call and adding a setUseCurl(always) call)

I don't think this is gonna work, because this also uses Libcurl.

Is the difference of 2 coming from the 2 newlines bewtween the header and the body?

**Comment by gggeek** [comment] 2020-05-30 12:25
"I don't think this is gonna work, because this also uses Libcurl" => correct, but you will be forcing curl to send an 'HTTP/1,0' request, which should force Apache to not use chunked encoding...

I am currently doing a round of tests with Apache, Nginx, Lighttpd on Debian 10 (php 7.3).
So far I tested with short responses (< 8K).
The behaviour of the response, when the php app sets/does not set/sets a wrong Content-Length header on its own, changes from server to server :-(

I am not sure about why there would be a difference of 2 bytes in content length between php and apache. As per the spec, the two NL between headetrs and body should never be accounted for.

A silly question: does your webserver's index.php file include extra whitespace  or carriage returns before the opening php tag / after the closing one?

**Comment by gggeek** [comment] 2020-05-30 15:31
First round of testing, results are in.

Setup:

Debian 10 for both cleint and server, testing localhost.
Client: curl (libcurl 7.64.0)
Apache 2.4.38 + mod_php
Lighttpd 1.4.53 + php-fpm
Nginx 1.14.2 + php-fpm

Tested http 1.1 and 1.0 requests, to a php page serving responses long 243 and 8001 bytes, each time with 3 permutations: a) php sends the Content-Length header, b) php does not send it, c) php sends it but with a wrong value.

Results:
- Nginx does do chunked encoding when php does not set the CL, for HTTP 1.1
- Nginx does neither chunked encoding nor add a CL when php does not set the CL, for HTTP 1.0
- Lighttpd always adds the missing CL for both HTTP 1.1 and HTTP 1.0 if php did not set it (I suspect a missing parameter to enable chunked encoding here)
- both Lighttpd and Nginx honour a wrong CL header set by php (they do not try to fix it)
- CE is only triggered when php is not sending the CL
- Apache is the only one which changes its behaviour for responses above and below 8K: below 8K it seems to be buffering the response, calculating the CL on its own and overriding the one from php (it does add it both for HTTP 1.1 and 1.0, when php either omits it or sets it wrong); over 8K it does the same as Nginx, namely use chunked encoding for HTTP 1.1 and neither CE nor CL for HTTP 1.0. Note that this could be due to either Apache code or mod_php code.

Summary:
- In all of the above tests, neither Apache nor PHP did ever get the CL wrong
- It seems that having php set the CL seems to be the best action for most cases
- Without usage of HTTPS, it seems that Apache responses are fine, ie. I could not reproduce the behaviour of having both CL and CE in a response

Next step: test with https

**Comment by gggeek** [comment] 2020-05-30 16:06
2nd round of tests, 1st result:

with a 8001 bytes response and Apache/mod_php, the results I get are the same as with plain http:
- with http11 and no CL, apache moves to CE
- with http10 and no CL, apache does not move to CE
- with both http11 and http10, with a wrong CL from php, the result seems truncated (this test did not involve parsing xml)

**Comment by henderikus** [comment] 2020-05-30 16:37
>A silly question: does your webserver's index.php file include extra whitespace or carriage returns before the opening php tag / after the closing one? Or a BOM?
No, what do you mean with BOM?

Do you also get a difference of 2 bytes in CL?

**Comment by gggeek** [comment] 2020-05-30 16:44
> Do you also get a difference of 2 bytes in CL?

No.
In fact I just did a test using the phpxlrpc lib both as client and as server, with https, and I did not manage to reproduce any of the problems that you seem to encounter :-(
- Apache does not seem to (erroneously) trigger chunked-encoding
- the Content-Length header in the response is correct enough for both curl to validate the response and libxml to parse it

**Comment by gggeek** [comment] 2020-05-30 16:49
The code I used for the test ^^ : https://gist.github.com/gggeek/b6b07a520a0b7318900fe72cd446f78c

**Comment by gggeek** [comment] 2020-05-30 16:53
PS: BOM = Byte Order Mark. A couple of bytes added to the beginning og utf8-encoded files, mostly by MS editing tools, and nowadays generally frowned upon

**Comment by henderikus** [comment] 2020-05-30 18:04
Does your Apache/mod_php also make the CL 245, when below 8k?

**Comment by gggeek** [comment] 2020-05-30 18:30
> Does your Apache/mod_php also make the CL 245, when below 8k?

No, it does not.

I thought about this, and I am inclined to think that the problem is that "something" on your server is adding 2 extra bytes to the response after the phpxmlrpc lib has done its job.

That would explain the symptoms:
- nginx respects the CL header set by php
- apache, under 8K, does not respect it, but recalculates the CL on the actual response length, and adds 2 bytes
- apache, above 8K, does not recalculate the resp length and lets through the one set by the lib

As I have a hard time thinking that the php `strlen` function is buggy, that leaves as prime suspects:
a) php code which gets run after the phpxmlrpc server has executed (and this includes newlines after php files closing tag)
b) other apache modules / unusaul config

**Comment by henderikus** [comment] 2020-05-31 13:25
I thought I isolated the issue, but unfortunate the 2 bytes was coming from our software. There was a function call in my test code which causes the 2 newlines... :(

The positive thing is there isn't a bug in the Library :)

**Comment by gggeek** [comment] 2020-05-31 15:37
All is well that ends well :-)

**Closed** 2020-05-31 15:38 UTC

**Comment by gggeek** [comment] 2020-05-31 15:39
ps: I presume that with the extra 2 newlines removed now all calls, work, even the ones bigger than *K using https

**Comment by henderikus** [comment] 2020-06-01 09:40
Yes all calls are working. Thanks for the help.
