### ISSUE TITLE
Problem with inflated

### ISSUE THREAD

**Issue by XharkTR** [gggeek/phpxmlrpc#69] opened 2019-02-07 08:29 UTC
For a request working fine in my coworkers pc, I'm getting `Invalid return payload: enable debugging to examine incoming payload (XML error at line 1, check URL)`. Debug returns an INFLATED RESPONSE that i'm not able to get acces to, but it seems correct. but also I'm getting this:

```
---GOT---
HTTP/1.1 200 OK
Date: Thu, 07 Feb 2019 08:09:13 GMT
Server: Apache/2.4.18 (Ubuntu)
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 957
Connection: close
Content-Type: text/xml;charset=none

‹íkoÚ0†¿÷WDý´Jíb;@Ê¨¢@i´*©¸ü€,¸m$’0'­¶?séE¹-£…œO`^|°ý>ãÈÖå¯x¡<q‘Eiòí”~%§—ý+æùC:ól™&—Ë@qöüD>>‹GÞ·!‚ß²8òàµ6ËÅc˜¯uâ\ô­$ˆyÿŽ‡¥®Ÿ¿¼4Jò>#”–º*YêæÒ‰¥nßþNGð;.xF‰ÉÏ’û>a¬×3tBtKÝVUŠ¦bÎ“½1tÚ©¯Åóèç#Ï‹›G6Š„Ö­/+ãÎây‘(5I‡„h€˜ËôzD'†	
ºRM>0bšDÓÅF¢$nF“–‰mÚ
ºR
---END---

HEADER: date: Thu, 07 Feb 2019 08:09:13 GMT
HEADER: server: Apache/2.4.18 (Ubuntu)
HEADER: vary: Accept-Encoding
HEADER: content-encoding: gzip
HEADER: content-length: 957
HEADER: connection: close
HEADER: content-type: text/xml;charset=none

```

**Comment by gggeek** [comment] 2019-02-07 10:54
Hello.
I fear that `charset=none` might confuse the client-side of the lib.
However, that would most likely give a different error...
One easy way to troubleshoot the problem is to enable/disable support for receiving compressed responses, via setting the corresponding flag in the client

**Comment by XharkTR** [comment] 2019-02-07 11:02
Doing  `$client->setAcceptedCompression("");`i'm not getting the baddly codified string, but i'm still getting the same error...
What trubbles me is taht i can see that im getting the responses but i dont know how to get it.
`$res->faultCode()` is true.

**Comment by gggeek** [comment] 2019-02-07 18:29
This seems indeed to be a charset encoding problem then. Do you have a way to send me the response payload, in its binary form? Or could I access the server to examine the responses?

**Comment by XharkTR** [comment] 2019-02-08 06:24
Unfortunatyl I couldn't, since is protected information... How can i acces de binary form of the response payload?

(thanks for your help, btw)

**Comment by XharkTR** [comment] 2019-02-08 09:12
I thing the problem is here:
```

**Comment by XharkTR** [comment] 2019-02-08 09:14
I hitnk the problem might be here(xmlrpc.inc line 2630):
```php
if (extension_loaded('mbstring')) {
    $data = mb_convert_encoding($data, 'UTF-8', $resp_encoding);
}
```
After that call to mb_convert_encoding, $data is not longer accesible.($resp_encodig is "NONE", ata that point).

**Comment by gggeek** [comment] 2019-02-08 11:39
'gzip' is not a valid value for `mb_convert_encoding`. Can you test instead if using 'auto' works? If so, I could think about adding some special-case code for when invalid charset declarations are found, such as in your case.
Tbh, I think that you should rather fix the server so that it does not emit the charset encoding header at all instead of saying `charset=none`

**Comment by gggeek** [comment] 2022-10-01 15:11
No feedback for over two years. Closing

**Closed** 2022-10-01 15:11 UTC
Labels: bug, waiting for feedback
